### ISSUE TITLE
Question: How to bind event handlers for custom events?

### ISSUE THREAD

**Issue by JesperWe** [peerlibrary/meteor-blaze-components#118]
The documentation for the new event handler bindings is a bit brief, and only use 'click' events in the examples, which are handled by binding with onClick. It would be helpful to document how to bind other events too. Can I always just capitalize the first letter and prepend "on", or what is the algorithm? For example, how would I bind the `shown.bs.collapse` [event in Bootstrap](http://getbootstrap.com/javascript/#collapse-events)?

**Comment by mitar** [comment]
> Can I always just capitalize the first letter and prepend "on", or what is the algorithm?

Yes.

But I have not tried with dots in the name, though. But yes, [everything which matches this regex](https://github.com/peerlibrary/meteor-blaze-components/blob/master/patch-compiling.js#L1) is considered event handler, and then [event name is generated here and attached with jQuery](https://github.com/peerlibrary/meteor-blaze-components/blob/master/client.coffee#L73). So if dots are correctly parsed by Spacebars and if jQuery correctly attaches custom events, then it should work.

The issue is that I think jQuery uses dots for their namespacing of events, no?

**Comment by mitar** [comment]
Oh, those are namespaces what Bootstrap uses. So it should work.

**Comment by mitar** [comment]
Have you tried? Does it work?

**Comment by JesperWe** [comment]
Oh, sorry for not replying. Yes it works as you describe.
Maybe worth adding a sentence to the documentation to describe the algorithm.

**Comment by mitar** [comment]
Do you want to propose a sentence? Pull request?

**Comment by JesperWe** [comment]
Done in #121

**Comment by mitar** [comment]
Perfect, thanks!
