### ISSUE TITLE
Blaze Components + Incremental DOM

### ISSUE THREAD

**Issue by alexandesigner** [peerlibrary/meteor-blaze-components#120]
@mitar What are the benefits we would have if it were rendered in Incremental DOM?

**Comment by mitar** [comment]
What you mean by incremental DOM? VirtualDOM?

**Comment by rclai** [comment]
I think he's talking about this: https://github.com/google/incremental-dom

**Comment by alexandesigner** [comment]
First of all i'd like to compliment you on the great job with Blaze Components... So nice!

That's right, Here is an excellent [article](https://medium.com/google-developers/introducing-incremental-dom-e98f79ce2c5f)

I believe it is a good approach and I would like to try on the Blaze Components, i'm curious to know where [Incremental DOM](https://github.com/google/incremental-dom) would fit..

**Comment by mitar** [comment]
I think this would be better opened against [Blaze](https://github.com/meteor/blaze), because it is something which is independent from this package and could be implemented at the Blaze level. But if you want, you can also try to do it directly at this level.

I see three options how you could integrate it. One is to hook into [animations hooks](https://github.com/peerlibrary/meteor-blaze-components#animations), but I doubt this will really work because at that level you have concrete DOM elements already ready to be inserted.

Another would be to implement an alternative [DOM backend](https://github.com/meteor/blaze/blob/master/packages/blaze/dombackend.js), but I also do not think this is the right way, because it seems it just handles how you append data and events to an existing DOM elements.

So I think you want to override [materializer](https://github.com/meteor/blaze/blob/master/packages/blaze/materializer.js). If incremental DOM has good API, this might be relatively straightforward to do.

**Comment by alexandesigner** [comment]
You're right. The direct implementation in the Blaze would be more appropriate.

In a way, my question was made precisely because Blaze Components is treading the path that I believe to be the future of Blaze ... I'm already thinking about how we can improve the approach of the DOM in the Blaze.

So if I want to do some experiments directly on the blaze the path would be override [materializer](https://github.com/meteor/blaze/blob/master/packages/blaze/materializer.js)? 

I'm going to do some experiments and then return with news, will be if the staff of the MDG would that matter?

**Comment by mitar** [comment]
> So if I want to do some experiments directly on the blaze the path would be override materializer? 

I would say in both cases this would be the path.

This could simply be an extra Meteor package which overrides default materializer for Blaze. So people who would like to try it out would just add your package.

**Comment by mitar** [comment]
@allanalexandre: If there is any internal Blaze API change needed for you to make it work at all (or better), feel free to make them in your fork of Blaze and then we will integrate them with official Blaze.

**Comment by alexandesigner** [comment]
All right, during those days i'm going to start the experiments, first of all i need to understand better how it works the Blaze and its API.

I will work initially with the idea of the package.

Thanks @mitar

**Comment by mitar** [comment]
Closing in favor for https://github.com/meteor/blaze/issues/45.
