### ISSUE TITLE
Example of mixin for two-way binding

### ISSUE THREAD

**Issue by comerc** [peerlibrary/meteor-blaze-components#133]
...like [ReactLink](https://facebook.github.io/react/docs/two-way-binding-helpers.html). Please :)

**Comment by comerc** [comment]
OK, [released](https://github.com/comerc/meteor-template-two-way-binding). :)

**Comment by mitar** [comment]
Cool. I have two comments:
- allow also template itself to be passed in, instead of assuming that it is always a template name, so resolve name only if input is not already an instance of the template
- you traverse whole children tree at render time, this is pretty inefficient (check how I do inline events, you might want to do something similar), also you probably go to children templates as well, you probably want to assure that you traverse only elements which are part of current template

**Comment by comerc** [comment]
I decided both issues. Thank you!
