### ISSUE TITLE
Template-level Subscriptions

### ISSUE THREAD

**Issue by Taik** [peerlibrary/meteor-blaze-components#16]
Hi! Thanks for the awesome package. I'm attempting to convert most of my site structure over. There's one issue that I need clarification on, and maybe you can help.

I see that component has access to the underlying template utility methods. Currently I am using subs-manager (https://github.com/meteorhacks/subs-manager) to manage and cache subscriptions. Are there any plans to support this? Or will I have to manually load and unload using onCreated / onDestroyed?

**Comment by mitar** [comment]
You can just call `@subscribe`, the same as you would call [template.subscribe](http://docs.meteor.com/#/full/Blaze-TemplateInstance-subscribe).

So I am not sure about your question though. Because subs-manager deals with route-level subscriptions. But you are talking about template/component level subscriptions?

So be careful, component level `subscribe` does not deal only with cleaning up things, but also makes various template methods (like `Template.currentData`, which you probably do not want to use with components, BTW) work.

So if you want to have some manager for component level subscriptions, I suggest that this could be an extended class or mixin of the `BlazeComponent` class. There is nothing like that yet and it will not be part of the base class (I am trying to keep it minimal). But probably we should create a set of useful mixins and this definitely sounds useful.

I think having component-level subscriptions is even better than route-level. But then you do not need manager to not subscribe too much on and off.

Feel free to create such a mixin/package and I can link it from the README page.

(Mixin could simply add a smarter subscription method to the component prototype, or even override the existing `subscribe` method.)

**Comment by Taik** [comment]
Thanks for the quick clarification! I will play around with creating a Mixin for it.

**Comment by mitar** [comment]
Structure of a mixin should probably be something like:

``` coffee
class SubsManagerMixin extends BlazeComponents
  mixinParent: (mixinParent) ->
    @extendSubscribe mixinParent if mixinParent
    super

  extendSubscribe: (mixinParent) ->
    originalSubscribe = mixinParent::subscribe
    mixinParent::subscribe = =>
       ...
```

**Comment by comerc** [comment]
@Taik I want to see your implementation, please.

Template-level Subscriptions - it is true way.

**Comment by mitar** [comment]
Template level subscriptions are already supported. What is not is doing is caching and managing subscriptions in a more efficient way.
