### ISSUE TITLE
Template Instance no longer available

### ISSUE THREAD

**Issue by jbaxleyiii** [peerlibrary/meteor-blaze-components#20]
I was working on a project with BlazeComponent 0.5.0 and everything was running smoothly.

I upgraded to 0.6.0 and now the reference of `this/@` has no template instance. The templates are not rendering as well. Any thoughts?

**Comment by mitar** [comment]
Why do you need access to the template instance, if you can share? I hope that there is no need to access it directly.

I moved `@templateInstance` to `@_componentInternals.templateInstance` with 6fee849141789f7c164f9792dba8154cbff7cb58. To minimize the number of fields components use on the instance to only one, `@_componentInternals`.

I am sorry that this broke things for you. But that should really be something internal you would not have to access during normal use. So I would like to learn more about your use case. Feel free to access it through `@_componentInternals`. I will not be moving it away anytime soon anymore.

Also, this should be just a cosmetic change, so everything should be rendering as it was.

**Comment by mitar** [comment]
Please confirm that it works once you start using `@_componentInternals` instead of `@templateInstance`.

**Comment by jirkamelichar** [comment]
Hi, I actually came across this problem myself. Here is what I'm trying to accomplish:

I'm building a set of components, which I can re-use to quickly build "table views" - that is a table with data, pagination component, page-size component, filter field component, etc.

The target use case is something like this:

```
<template name="MyTableView">
{{> Pagination}}
<table>
  <th>
    <tr>Name</tr>
    <tr>Address</tr>
  </th>
  {{#each data}}
    <tr>
      <td>{{name}}</td>
      <td>{{address}}</td>
    </tr>
  {{/each}}
</table>
{{> PageSize}}
</template>
```

Where MyTableView is a component with a Mixin, which handles template level subscription and holds the current state (page index, page size, etc.)

Because I'd like to avoid having to pass "bridge variables" to the Pagination and PageSize components, like this:

`{{> PageSize pageIndex=pageIndex pageSize=pageSize totalCount=totalCount}}`

I want to have the PageSize component access parent template instance variables and read/write to the pageIndex (and other) "table view state variables". 

I know that I can now use the `@_componentInternals.templateInstance`, but maybe there is a better way of "connecting" the components (avoiding global state).

Thank you

**Comment by kostko** [comment]
> I want to have the PageSize component access parent template instance variables and read/write to the pageIndex (and other) "table view state variables".

Do you mean something like `@componentParent()` to get the parent component instance? Then you can access the data context, variables and methods on that component instance.

**Comment by jirkamelichar** [comment]
Thank you Jernej - that's exactly what I needed. I missed it in the documentation.
