### ISSUE TITLE
Simplify mixins API

### ISSUE THREAD

**Issue by mitar** [peerlibrary/meteor-blaze-components#3]
I think we should remove `callFirstMixin` method. While it helps with the common case, I think that `getFirstMixin` is enough. You can always do `.getFirstMixin('property')?.property()`. This would also give you an exception if `property` is not a function. Which we currently ignore in `callFirstMixin` and return `undefined`. Which makes it impossible to distinguish between an error and returned value `undefined`.

`callMixins` and `foldMixins` are interesting, but maybe they should not be part of the core API. Instead, a more low-level method could be offered:

``` coffee
getNextMixin: (mixin, propertyName) ->
```

This would return the next mixin with `propertyName` after the `mixin` mixin. In some way this is similar to `super`, just that it moves across mixins. So from a component you call:

``` coffee
foo: ->
  @getFirstMixin('foo')?.foo()
```

And that mixin can then do:

``` coffee
foo: ->
  @mixinParent().getNextMixin(@, 'foo')?.foo()
```

In some way, mixins themselves control the traversal. Instead of caller controlling when calling `callMixins` and `foldMixins` (it goes over all mixins no matter what).

And `getFirstMixin('foo')` could be simply the same as `getNextMixin(null, 'foo')`. Or we should have `getFirstMixin(propertyName, [mixinToSearchFrom])`. Or `getMixinWith(propertyName, [mixinToSearchFrom])`?

(What would be a way then to implement `callMixins` and `foldMixins` using `getFirstMixin` and `getNextMixin`?)

**Comment by mitar** [comment]
Decided to go with `getMixinWith: (afterMixin, propertyName)` and `callMixinWith: (afterMixin, propertyName, args...)`.

**Comment by offthegrass** [comment]
(Mixins are new to me, so this may be flawed / I may have misunderstood)

I think the most intuitive structure would be:

`getMixin: (MixinName, [methodNames])`

`callMixin: (MixinName, methodName, args)`

I don't think you need to include `First` - just make it clear in the docs that this targets the first matching mixin, like Blaze.find.

**Comment by offthegrass** [comment]
also, `callFirstWith` is ambiguous - it could be interpreted as first component.

**Comment by mitar** [comment]
Yes, `getFirstWith` can return both a component or a mixin. So `getMixin` is not really correct in this case. `callFirstWith` is then analogous.

So yea, I am not satisfied the most with this naming, but it was the best from the bad ideas. If you have a better proposals, keep them coming. :-)

We could name it also `getRight` and `callRight`. :-) So, just something abstract. (See the mixins diagram to understand why "right".)

**Comment by offthegrass** [comment]
`getRight` could be misinterpreted as 'get correct' rather than 'to the right of' (or below, depending on how you visualise it)

My initial thoughts are that there needs to be a clearer line between mixins and components. For example, don't think they should share functions as with `getFirstWith`.

Have a look at this diagram:
![screen shot 2015-04-22 at 13 15 54](https://cloud.githubusercontent.com/assets/9323637/7274103/c7952ec2-e8f1-11e4-82ab-f42a5ef010b2.png)

We could then have separate methods such as

`BlazeComponents.getMixin` or `BlazeComponents.addMixin`

 to import, so you wouldn't have to add Mixin to the end of every name, and 

`callMixinMethod(mixinName, mixinMethod)`

where if the name is null, it searches in the order they are defined inside the component (`D - E - F, A - B - C`), which is how it currently works anyway.

**Comment by mitar** [comment]
Yes, this is a good question if we should split mixins and components. There could be some helper functions which would be meaningful only for mixins and we could add them there.
