### ISSUE TITLE
Q: Two or more components sharing one mixin

### ISSUE THREAD

**Issue by rclai** [peerlibrary/meteor-blaze-components#45]
Is it possible for two or more components to share a mixin's data without having to instantiate multiple instances of that mixin or does it work like this already?

For example, I'd like this mixin to be like a data source that these different components read from.

**Comment by mitar** [comment]
You could do something like:

``` coffee
dataSource = new ReactiveVar null

class Mixin extends BlazeComponent
  foobar: ->
    dataSource

class Component1 extends BlazeComponent
  mixins: ->
    [Mixin]

class Component2 extends BlazeComponent
  mixins: ->
    [Mixin]
```

No? :-)

You could do maybe even something like:

```
mixinInstance = new Mixin dataSource

class Component1 extends BlazeComponent
  mixins: ->
    [mixinInstance]

class Component2 extends BlazeComponent
  mixins: ->
    [mixinInstance]
```

But this will not really work because each mixin instance currently can have only one `mixinParent`.

**Comment by mitar** [comment]
After more thought I do not think this is a good pattern to support (and it would also break backwards compatibility). So if you need some common object between multiple components to use as a state you can simply do that without mixins? So simply use whatever object you want for this common state. For example, a Minimongo collection.

Alternatively, you can pass an object to a mixin constructor to serve as its state, and you can pass the same object to multiple mixins then. So the example from the tutorial:

``` javascript
mixins() {
  return [new StorageMixin(Values, 'value', () => {this.data().id)}];
}
```

Here `Values` collection is being used as a state.

I know that this might not be the answer you wanted because sometimes this would mean that you have to create a mixin class just so that it can pass all method calls directly to your state, but maybe such a layer of abstraction is a good thing anyway, because then you can change state later on, while keeping the mixin interface.

And I understand that for the first approach, a common object between components, it would be great to be able to reuse mixin ecosystem and just specify an mixin instance multiple times. But I think such a thin mixin wrapper around your common object instance is a good enough approach while keeping the design

**Comment by mitar** [comment]
After a bit more thought I think we can relax checks in core a bit so if one wants to have such a mixin you can do it yourself. For example, have such a base class where you override `mixinParent` with a custom implementation which supports multiple parents:

``` coffee
class MultiMixinBase extends BlazeComponent
  # Overriding mixinParent with a version which supports multiple parents.
  mixinParent: (mixinParent) ->
    @_componentInternals ?= {}

    # Setter.
    if mixinParent
      @_componentInternals.mixinParents ?= []
      @_componentInternals.mixinParents.push mixinParent
      # To allow chaining.
      return @

    # Getter.
    @_componentInternals.mixinParents or []

  onDestroyed: ->
    super

    # We do not know which component was destroyed, but we can find it out.
    @_componentInternals.mixinParents = _.reject @_componentInternals.mixinParents, (mixinParent) ->
      mixinParent.isDestroyed()
```

Only do have in mind that now your `mixinParent` returns `[]` inside this mixin, so you have use your code like this if you want to talk to your mixin parent (or parents).

**Comment by mitar** [comment]
This is also a candidate mixin for a package of mixins.

**Comment by rclai** [comment]
Whoa, that looks cool. I'll have to try it out some time. Thanks.
