### ISSUE TITLE
Keep template hooks intact

### ISSUE THREAD

**Issue by DominikGuzei** [peerlibrary/meteor-blaze-components#53]
Hey there,
When I use blaze-components it seems like I can't register "normal" blaze template hooks anymore:

``` coffeescript
class UrlForm extends BlazeComponent
  @register 'UrlForm'
  onCreated: -> console.log 'From Component'

# later
Template.UrlForm.onCreated -> console.log 'From normal hook'
```

`'From normal hook'` is never logged in this case, only `'From Component'`.
This is pretty bad because other packages rely on the these standard hooks to work correctly.
Using Meteor 1.1.0.2

**Comment by mitar** [comment]
Templates are used only for content. If you want to use some other template with traditional behavior, then wrap it into the component:

``` handlebars
<template name="Component">
  {{> traditionalTemplate}}
</template>
```

``` coffee
Template.traditionalTemplate.onCreated -> console.log 'TEST'
```

You cannot really use template hooks from traditional templates anyway in components, because they work differently. In Blaze Components a component instance is bound to `this`, for traditional templates you get a template instance bound to `this`. Same goes for template helpers. Then template helpers would behave differently to component methods.

So I think it is better to keep these two worlds cleanly separated than trying to bridge them and then you would have to think in which world you are.

**Comment by DominikGuzei** [comment]
The problem is that some people like to use `blaze-components` together with other packages like `space:ui` which fulfill different purposes.

Here is the original issue that made me look closer: https://github.com/CodeAdventure/space-ui/issues/27

`space:ui` only hooks into the template callbacks and adds the mediator instance to the template instance, so it doesn't care which context it is in. The mediator also doesn't care because it is just a bridge to other code parts.

**Comment by mitar** [comment]
If you do not want to write wrapper component templates, you can also define them dynamically. Something like (untested):

``` coffee
class UrlForm extends BlazeComponent
  @register 'UrlForm'

  template: ->
    template = super
    new Blaze.Template "BlazeComponent.Include.#{ @componentName() or 'unnamed' }", =>
      template
```

**Comment by DominikGuzei** [comment]
Ok thanks, I will let the other ones decide how they want to integrate the two packages, there are multiple workarounds anyway. Although it would be pretty awesome to make `space:ui` and `blaze-components` more compatible.

**Comment by mitar** [comment]
Sure. I would love to see that as well.

**Comment by mitar** [comment]
So I will close this with pull request welcome. Or probably this should be a separate package. Feel free to open tickets with questions if you need any help.

**Comment by mitar** [comment]
See #71 for a ticket about implementing this.
