### ISSUE TITLE
Application architecture confusion

### ISSUE THREAD

**Issue by slopSurfer** [peerlibrary/meteor-blaze-components#60]
I have been using Blaze components for only one week and really like it.  I do have a couple of questions and I hope posting here is ok.

I have been developing an app for the last couple months which is a Human Resources Recruitment System.  Im using Blaze in the UI but finding a component based architecture would be much better as the complexity grows.  Hence my interest in Blaze components.

The following screen shot is a basic Job Application form which is composed of several Blaze Components representing corresponding mongo collections. for example a component for Job Application, another for Contact Information, Add a Resume and one for the entire form.

https://dl.dropboxusercontent.com/u/25440531/jobApplicationScreen.png

So here's a couple of probably fairy basic questions.

To save and send the application I click the 'Send Application' button.  
1.How can I call a 'save' method in the child components from the parent template/form ( ie make  public functions that I can access from the parent?). I would like to do this so that the child component is responsible for its own subscriptions and Meteor.call() s to save the data in order to make it totally independent of the form in which it resides.
2. Is it better to use jQuery to get the child components data from their forms and use a 'save' method in the parent template/component? (not my preferred choice)
or
3. call a public method in the child component from the parent component to get the child components data? ( I would prefer this approach)
4. How can/should I call a method / function in the parent form/component if required?

Any help with any of these questions would be really appreciated.  If this is not the correct forum in which to ask these questions please direct me where to go.

Thanks

**Comment by mitar** [comment]
> How can I call a 'save' method in the child components from the parent template/form ( ie make public functions that I can access from the parent?). I would like to do this so that the child component is responsible for its own subscriptions and Meteor.call() s to save the data in order to make it totally independent of the form in which it resides.

Your child component should have a public method exposed. Then you use `componentChildren` or `componentChildrenWith` in the parent component to find a child component you are interested in. This goes only one level deep, so if your children component is deeper, you should search recursively. (There are no helper functions provided for you to do so, but it is not so hard to do them.) Once you find that children component, you call the public method on it.

> Is it better to use jQuery to get the child components data from their forms and use a 'save' method in the parent template/component?

No, you can navigate up and down the component hierarchy yourself. You do not need to use jQuery. But yea, some helper functions similar to jQuery could be useful. So that you could do things like `componentDescendantsWith` and similar things. But I am reluctant to provide that in core, it should probably be an extra package.

`componentChildrenWith` hints at an API. So what we are using is for example components where you set their `this.id` field to some ID you want. And then you can search for the children component with that ID with `componentChildrenWith`.

> call a public method in the child component from the parent component to get the child components data?

Yes, it looks cleaner for me as well.

> How can/should I call a method / function in the parent form/component if required?

You just have to get hold of a component instance. There are many ways to do so. You can navigate using `componentChildren`, `componentDescendantsWith`, `componentParent`. You can even use jQuery DOM element and then get the component for that DOM element using `getComponentForElement`. You can store component instances yourself somewhere.

> Any help with any of these questions would be really appreciated. If this is not the correct forum in which to ask these questions please direct me where to go.

It is. Questions are welcome here.

**Comment by slopSurfer** [comment]
thanks for the detailed response mitar.

I have generally accomplished what I set out to do but am unsure if I did the 'correct' way.

Briefly I have a base Mixin then a BlazeComponent, which uses that Mixin. I have another BlazeComponent derived from the previous BlazeComponent. To call the 'saveResume' method from the standard Blaze template button click. I resorted to creating a prototype method on the base Mixin (which is called on the button click). I have also created some other public methods on the base Mixin in the same way.  It works fine but Im not sure of its 'correctness'.

I have used :
 onSaveResumeFile: function (event) {
        this.callFirstWith(this, 'saveResume');
    }

on some private events in derived BlazeComponents, which I like.  I just cant seem to find how to create a public method on the derived BlazeComponent and use something similar to call a private method in the base Mixin.  I know Im missing something elementary but after many hours cant work out what.

I cant figure out how to use componentChildren, componentDescendantsWith, componentParent etc in the above example.  If I call them with **super**.componentChildren / parent its returning null.  If you could point out to me the solution I would really appreciate it.

**Comment by mitar** [comment]
First you have to move from a mixin to a component using `mixinParent` method.

**Comment by slopSurfer** [comment]
ok thanks. I look at that very soon.

cheers
