### ISSUE TITLE
Automatically copy over template helpers and event handlers from existing templates

### ISSUE THREAD

**Issue by mitar** [peerlibrary/meteor-blaze-components#71]
When Blaze Component is made from an existing template, it would be great to copy over template helpers and event handlers. The downside is that behavior of them is a bit different, like binding of `this` is different, but we could probably pull this off.

How do people feel about this feature? Would that be something which is good or people think it would make things more confusing?

**Comment by mitar** [comment]
See #70 for more discussion.

**Comment by mitar** [comment]
Also template hooks.

**Comment by DominikGuzei** [comment]
I think this would be more confusing than helping anyone. Also it would not quite work because of the different context of `this` within templates vs. components. Let's just agree that blaze is a horrible solution for object oriented programming and makes it as complicated as possible to build a good component system on top. BlazeComponents basically is what blaze should have been, a solid foundation with advanced features.

I would not recommend anyone to write standard blaze templates + helpers anymore. It even seems as if MDG realized that, since they are not really actively bringing out exciting features for blaze but support React / Angular now.

**Comment by mitar** [comment]
I think it is doable with pretty good consistency: if you are extending empty templates (what you are probably doing anyway, if you are use pure Blaze Components) then it will be the same as now. But if you are extending an existing template (which you cannot control) you can bridge into Blaze Components word and extend it and override some stuff you want.

I also thought that it will be complicated to implement, but I am now seeing that it might be easier than I thought.

**Comment by DominikGuzei** [comment]
Yeah of course it's possible, but i don't see any benefit - it's also not much work to copy over the helpers / events etc. and make a blaze component out of it. If you extend an existing template you have spread your UI handling logic in two separate places that you then need to understand / keep in mind the differences etc. Not seeing the real-world use case where this would be of great value.

**Comment by mitar** [comment]
I think an example was extending [accounts templates](https://github.com/meteor-useraccounts/core) in #70 and also your ticket #53.

I agree this is an anti-pattern and I documented that in the README. But I think it is OK to support it.

**Comment by mitar** [comment]
Ah, I discovered that my first approach didn't work well. So now preexisting template helpers are not copied over to the component, but are simply searched next, if component does not contain the property. So behavior is now similar (component properties have precedence, and we fail back to any preexisting template helpers), but you sadly can just override preexisting template helper and cannot call `super` to call it and extend/wrap it. :-( Which was my main goal. The issue is that component has `template` method as instance method and not class method so we cannot know which template to use when we are creating an instance. And also the question where in the prototype chain one would want to inject those template helpers. If at the end (latest class in the inheritance) then you cannot really extend it and `super` works badly. Ideally you would have it at a base class. But you cannot just change the base class because that changes it for all other components who might be inheriting from the same base class. So I do not know how to make it so that you can nicely extend it. At the moment you can just override them. (Of course you can call manually the helper inside your component method. But that is not so nice as calling `super`.)

**Comment by DominikGuzei** [comment]
Yeah, as i said: blaze templates and their API just suck big times in regard to flexibility / extensibility. We already removed any code using blaze templates directly from our space framework because of that. I don't want to support anti-patterns and things where people will shoot themselves into their feet when their project gets bigger :wink:

**Comment by mitar** [comment]
Yea, but I think this is a good way to help people transition. But yea, it is now much uglier than I anticipated.
